### ISSUE TITLE
make capital H provide more hints

### ISSUE THREAD

**Issue by stunder** [kppullin/hubot-trivia-game#1]
Do I really need to explain 🗡

**Comment by stunder** [comment]
This doesn't look extended to me!!!!

![image](https://user-images.githubusercontent.com/4008640/33224412-10cfaf38-d11e-11e7-9b0c-64c668e0e87c.png)

**Comment by kppullin** [comment]
"Working by design"

Current logic expands the range by 40% of the remaining chars.  My eyes are bad but this looks like the first case is `6 unknown * .4` = 2 (rounding down).  Next one is `4 unknown * .4` = 1.

Any ideas to improve?  We could set a floor at 2 chars, so that it's always at better than the normal `!hint`.

**Comment by stunder** [comment]
Nope after I made such a stupid post I kind of figured that is what you did.  Seems like the smart/best option IMO. I'll stop bitching about your logic, who am I to ever question the mighty Pullin!!!!

**Comment by kppullin** [comment]
It's all for the lulz.  I went ahead and made it show at least 2 chars in "extended" hint mode.
